### ISSUE TITLE
Add Ops interface for editing and localizing navigation

### ISSUE THREAD

**Issue by k7hpn** [MCLD/ocuda#337]
Add the interface for adding/editing navigations for the public site in Ops.

## Notes

- Navigation is stored in the Promenade database, tables `Navigations` and `NavigationTexts`
- There are different parameters used depending on which menu an item belongs to (e.g. `ChangeToLinkWhenExtraSmall`, `HideTextWhenExtraSmall`) - understand when these are used to ensure they are only presented as options on menus when they are relevant.
- Navigation data structures are already prepared for localization and changes should support localization (e.g. `NavigationTexts` should permit setting up multiple languages)
- There are four navigation top-level parents as configured in SiteSettings: Top Navigation Id, Middle Navigation Id, Left Navigation Id, and Footer Navigation Id
- Nav is cached and you may need to clear cache as you edit items to see them reflected in Promenade if you are running both sites concurrently locally
- Minimize use of JavaScript, keep code simple and readable
- Add and edit can probably share a form
- Delete should always show a modal pop-up to verify
- Follow the page templates of Pages in Site Management or Digital Displays in Content Management (navigation in the top right, a row of pills if necessary for different areas, standardized icons in the right-most column titled "Actions", etc).

## Tasks

- [ ] Add a card to SiteManagement in Ops for navigation and the management pages
- [ ] That link should go to a page with a list of the four navs. If they are present, each is a button to edit that nav, if not there's a button to add that nav. Test from an empty database to ensure initial adding works.
   - When creating, automatically adjust the Site Setting to have the proper id.
   - All four navs shouldn't be required, i.e. from a clean database you could just have middle nav and no other. I believe Promenade will handle that situation properly, if not notate that and fix it or assign it as a task for part of this issue.
   - Parent menu items are mostly contentless other than name and ID, you can see samples in a production database.
   - Once management happens completely from this interface we will probably remove the ability to manually change those site settings.
- [ ] Add the ability to add and edit menu items
   - Menu items have different parameters - some are used depending on which menu they are, some are ignored
   - Examine the options and ensure we only prompt for functional options depending on which menu is added to or edited
   - Every item (except those in item 2 above, the top-level ones) must have an associated NavigationText record aligned with the default language (which can be found in the Languages table with IsDefault set to true)
   - Menu items can be nested one-deep (e.g. Events -> All Events or Locations & Hours -> Find My Library), the parent item's id is place in the child item's `NavigationId` field
   - The `NavigationText` property `title` should be required for items which are just icons (`Navigation` property `Icon` is set and `NavigationText` property `Label` is `NULL`) but set to `NULL` for items which are not just icons.
   - The `NavigationText` property `AriaLabel` should always be `NULL` and probably eventually removed.
- [ ] Add the ability to delete menu items
   - When deleting, the pop-up should show how many child objects the selected item have
- [x] ~~Modify Promenade to not display the `AriaLabel` text - if the `Navigation` value `TargetNewWindow` is set then the `aria-label` on the link should contain the content `(opens in a new window)`~~

**Comment by iafb** [comment]
Issue being worked on in branch [feature/prom-navigation-management](https://github.com/MCLD/ocuda/tree/feature/prom-navigation-management)
