### ISSUE TITLE
Improve eMedia management and internationalization

### ISSUE THREAD

**Issue by k7hpn** [MCLD/ocuda#341]
Enhance eMedia funcitonality to support administration and internationalization.

## Notes

- Administration of eMedia is incomplete
- eMedia is cached and you may need to clear cache as you edit items to see them reflected in Promenade if you are running both sites concurrently locally
- Minimize use of JavaScript, keep code simple and readable
- Add and edit can probably share a form
- Delete should always show a modal pop-up to verify
- Follow the page templates of Pages in Site Management or Digital Displays in Content Management (navigation in the top right, a row of pills if necessary for different areas, standardized icons in the right-most column titled "Actions", etc).

## Tasks

- [ ] Modify the Emedia index to appear and function as the index of Pages or Digital Displays does
- [ ] Modify Emedia management to allow adding/editing of all relevant fields and incorporate localization
- [ ] Modify Emedia Categories index to appear and function as the index of Pages or Digital Displays does
- [ ] Modify Emedia Category management to allow adding/editing of all relevant fields and incorporate localization
- [ ] Ensure deleting a category shows a warning with if that category is in use first (e.g. "This category is in use in x eMedia entires, are you sure you want to remove it") and that it deletes the relationships as well as the category itself
